In [2]:
import numpy as np
import torch
import sys
from torch.utils.data import TensorDataset, DataLoader
import matplotlib.pyplot as plt
from torch import nn
from torch import optim
from torch.autograd import Variable
import torch
import torchvision
import torchvision.transforms as transforms
from sklearn.model_selection import train_test_split
import copy
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = str(7)

from collections import OrderedDict
from copy import deepcopy
from torch.autograd import Variable
from torch.nn import functional as F
from torch import autograd
from torchvision import datasets,transforms
from sklearn.utils import shuffle

In [3]:
from dataloader_cifar10 import get_cifar10

In [4]:
train_data_loaders, test_data_loaders, validation_data_loaders = get_cifar10(classes=[5,5],valid_rate = 0.05, batch_size=128, seed = 0)

Files already downloaded and verified
Files already downloaded and verified


In [10]:
for x,y in train_data_loaders[0]:
    print(y)

tensor([2, 1, 4, 1, 1, 0, 1, 4, 3, 1, 1, 2, 4, 4, 2, 1, 2, 1, 4, 2, 3, 4, 0, 3,
        0, 2, 2, 1, 1, 1, 4, 2, 1, 1, 3, 1, 4, 2, 2, 4, 0, 4, 4, 2, 1, 0, 1, 3,
        0, 2, 4, 0, 1, 1, 0, 0, 3, 1, 4, 2, 2, 1, 1, 0, 0, 1, 4, 2, 1, 1, 4, 0,
        2, 2, 0, 2, 1, 1, 1, 2, 2, 1, 4, 2, 0, 4, 4, 1, 2, 4, 4, 0, 1, 2, 0, 4,
        3, 1, 1, 0, 1, 4, 4, 4, 2, 3, 3, 0, 1, 0, 1, 4, 1, 3, 4, 4, 2, 4, 2, 4,
        2, 3, 1, 0, 4, 3, 4, 2])
tensor([2, 1, 3, 3, 2, 1, 4, 1, 1, 0, 1, 3, 2, 1, 4, 3, 3, 2, 4, 2, 2, 2, 1, 4,
        4, 3, 2, 0, 1, 4, 1, 3, 2, 2, 0, 4, 4, 0, 4, 2, 2, 2, 1, 0, 2, 0, 0, 2,
        2, 0, 2, 1, 3, 4, 1, 3, 0, 1, 2, 0, 2, 3, 2, 0, 3, 1, 0, 0, 4, 1, 2, 4,
        2, 1, 0, 4, 3, 3, 1, 3, 4, 3, 2, 3, 1, 2, 0, 4, 2, 2, 2, 1, 2, 3, 1, 2,
        1, 4, 0, 1, 2, 0, 3, 2, 1, 3, 1, 3, 1, 0, 0, 0, 2, 3, 0, 4, 4, 2, 1, 0,
        0, 1, 3, 3, 2, 3, 1, 3])
tensor([4, 1, 1, 1, 4, 0, 1, 4, 3, 2, 4, 3, 4, 0, 1, 0, 2, 0, 3, 2, 3, 2, 1, 0,
        2, 1, 1, 1, 4, 1, 0, 0, 1, 3, 3, 2, 3, 1, 2, 4